import Link from 'next/link';
import { ArrowDownRight, ArrowUpRight, Box, Compass, VolumeX } from 'lucide-react';
import galleries from '@/data/galleries.json';
import { exhibits } from '@/lib/getExhibits';
import { ExhibitCard } from '@/components/gallery/ExhibitCard';
import { Reveal } from '@/components/ui/Motion';

const indiaVideo = 'https://res.cloudinary.com/dwemivxbp/video/upload/v1788027504/Watch_India_in_4K_One-Minute_Cinematic_Travel_Video_India_Places_to_Visit_-_Aishwarya_TV_1080p_h264_a3upaa.mp4';

export default function Home() {
  const monuments = exhibits.filter(e => e.id !== 'chandrayaan-missions');
  const modern = exhibits.find(e => e.id === 'chandrayaan-missions');
  return <div>
    <section className="relative isolate min-h-screen overflow-hidden text-white">
      <video className="absolute inset-0 -z-20 h-full w-full object-cover" autoPlay muted loop playsInline preload="metadata" aria-hidden="true"><source src={indiaVideo} type="video/mp4" /></video><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black/60 via-black/30 to-transparent" />
      <div className="mx-auto grid min-h-screen max-w-6xl items-end gap-12 px-5 pb-16 pt-28 md:grid-cols-[1.05fr_.95fr] md:items-center md:pb-20"><Reveal><p className="mb-6 text-xs font-bold uppercase tracking-[.25em] text-[#f4cf75]">A living archive · Est. 2026</p><h1 className="display max-w-3xl text-6xl font-bold leading-[.88] md:text-8xl lg:text-9xl">India,<br /><i className="font-normal text-[#f4cf75]">remembered.</i></h1><p className="mt-8 max-w-lg text-lg leading-8 text-white/80">Walk through five thousand years of ideas, artistry, resistance and discovery. Curated for the endlessly curious.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#galleries" className="focus-ring inline-flex items-center gap-3 rounded-full bg-[#f4cf75] px-6 py-4 text-sm font-bold text-[#2f211b] transition hover:bg-white">Explore the collection <ArrowDownRight size={17} /></Link><Link href="/atlas" className="focus-ring inline-flex items-center gap-3 rounded-full border border-white/60 bg-black/20 px-6 py-4 text-sm font-bold text-white backdrop-blur transition hover:bg-white hover:text-[#2f211b]"><Compass size={17} /> The Historical Atlas</Link></div></Reveal><Reveal className="hidden md:block"><div className="ml-auto max-w-md border-y border-white/60 py-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#f4cf75]">The collection</p><h2 className="mt-5 font-display text-4xl italic leading-tight">A doorway into the stories that shaped a civilization.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/75">From the Great Bath of Mohenjo-daro to Chandrayaan-3, encounter India through objects, places and ideas.</p><div className="mt-7 flex items-center gap-8 text-xs font-bold uppercase tracking-wider text-white/70"><span><strong className="block text-2xl text-white">04</strong>3D objects</span><span><strong className="block text-2xl text-white">03</strong>eras explored</span></div></div></Reveal></div><div className="absolute bottom-5 right-5 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white/70"><VolumeX size={16} /> Ambient film · muted</div><div className="absolute bottom-5 left-5 hidden gap-8 text-xs font-bold uppercase tracking-wider text-white/80 md:flex"><span className="text-[#f4cf75]">India 360</span><span>Heritage</span><span>People</span><span>Ideas</span></div>
    </section>
    <section id="galleries" className="mx-auto max-w-6xl px-5 py-24"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow">Explore by era</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">Rooms of memory</h2></div><span className="hidden text-sm text-[#806d60] md:block">01 — {String(galleries.length).padStart(2, '0')}</span></div><div className="grid gap-5 md:grid-cols-2">{galleries.map((g, i) => <Link key={g.id} href={`/galleries/${g.id}`} className="group focus-ring relative min-h-[205px] overflow-hidden rounded-2xl p-7 text-white shadow-museum transition hover:-translate-y-1 hover:shadow-xl" style={{ backgroundColor: g.colorTheme }}><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full border-[25px] border-white/10" /><p className="relative text-xs font-bold uppercase tracking-[.2em] opacity-70">0{i + 1}</p><h3 className="relative mt-14 text-3xl font-bold">{g.name}</h3><p className="relative mt-2 max-w-sm text-sm leading-6 text-white/80">{g.description}</p><ArrowUpRight className="absolute bottom-7 right-7 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></Link>)}</div></section>
    <section className="bg-[#efe5d7] px-5 py-24"><div className="mx-auto max-w-6xl"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow">Flagship objects</p><h2 className="mt-3 text-4xl font-bold">Look closer</h2></div><Link href="/search?only3D=true" className="hidden items-center gap-2 text-sm font-bold text-maroon md:flex">All interactive pieces <ArrowUpRight size={16} /></Link></div><div className="grid gap-7 md:grid-cols-3">{monuments.map(e => <div key={e.id} className="relative"><ExhibitCard exhibit={e} /><span className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-ink px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white"><Box size={12} /> Interactive</span></div>)}</div><div className="mt-24 grid items-center gap-10 border-t border-[#d5c3b0] pt-16 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Section 02 · Path to modernity</p><h3 className="mt-4 text-4xl font-bold leading-tight">From stone to stars.</h3><p className="mt-5 max-w-sm text-base leading-7 text-[#766459]">A new chapter begins with India’s journey beyond Earth. Explore the mission, its instruments and the landing that made lunar history.</p><Link href={`/exhibits/${modern?.id}`} className="mt-7 inline-flex items-center gap-2 rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white">Explore Chandrayaan <ArrowUpRight size={16} /></Link></div><div className="relative md:pl-8"><ExhibitCard exhibit={modern!} /><span className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-ink px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white"><Box size={12} /> Interactive</span></div></div></div></section>
  </div>;
}
